[INFRA] chore : Jenkinsfile 수정

diff --git a/server/api-gateway/Jenkinsfile b/server/api-gateway/Jenkinsfile
--- a/server/api-gateway/Jenkinsfile
+++ b/server/api-gateway/Jenkinsfile
@@ -70,7 +70,19 @@ pipeline {
                 script{
                     sh "docker rm -f api-gateway || true"
                     sh "docker pull \${repository}:api-gateway-\${BUILD_NUMBER}"
-                    sh "docker-compose -f server/api-gateway/docker-compose.yml -p api-gateway up -d --build"
+                    dir("./server/api-gateway") {
+                        sh '''
+                        if ! command -v docker-compose &> /dev/null
+                        then
+                            echo "docker-compose not found, installing..."
+                            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                            sudo chmod +x /usr/local/bin/docker-compose
+                        else
+                            echo "docker-compose is already installed."
+                        fi
+                        '''
+                        sh "docker-compose -f server/api-gateway/docker-compose.yml -p api-gateway up -d --build"
+                    }
                 }
             }
         }
